name: PHP CI and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HOST: "52.23.238.3"
      USER: "ubuntu" 
      PATH: "/home/ubuntu/vv/"
      DB_USER: "admin"
      DB_HOST: "database-2.c5essse68gdr.us-east-1.rds.amazonaws.com"
      DB_PASS: "HamzaImran12345"
      DB_PORT: 3306
      DB: "database-2"

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up PHP 8.2
    - name: Set up PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    # Step 3: Install PHP dependencies
    - name: Install PHP dependencies
      run: composer install

    # Step 4: Set up Node.js (for npm)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 5: Install Node.js dependencies and build
    - name: Install Node.js dependencies & build
      run: npm install && npm run build

    
    

     # Step 8: Deploy the application to a remote server
    - name: Deploy to Remote Server
      env:
        HOST: ${{ env.HOST }}
        USER: ${{ env.USER }}
        SSH_KEY: ${{ secrets.SECRETS }}
      run: |
        

        # Ensure SSH directory and key
        mkdir -p ~/.ssh && echo "$SSH_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
        
        # Add host to known_hosts and check variables
        [ -z "$SSH_KEY" ] && echo "SSH_KEY is not set" && exit 1
        [ -z "$HOST" ] && echo "HOST is not set" && exit 1
        ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts
        
        # Rsync and run commands on remote server
        rsync -avz --exclude='node_modules' --exclude='.git' ./ "$USER@$HOST:/home/ubuntu/vv" && \
        ssh "$USER@$HOST" 'cd /home/ubuntu/vv && php artisan migrate --force && php artisan config:cache && php artisan route:cache' || \
        { echo "Deployment failed"; exit 1; }
        
        echo "Deployment completed!"
