name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up PHP 8.2
    - name: Set up PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    # Step 4: Run tests
    - name: Run tests
      run: php vendor/bin/phpunit

