name: PHP CI and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up PHP 8.2
    - name: Set up PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    # Step 3: Install PHP dependencies
    - name: Install PHP dependencies
      run: composer install

    # Step 4: Set up Node.js (for npm)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 5: Install Node.js dependencies and build
    - name: Install Node.js dependencies & build
      run: npm install && npm run build

    # Step 6: Run database migrations (ensure database is accessible)
    - name: Run database migrations
      run: php artisan migrate --force

    # Step 7: Deploy the application to a remote server
    - name: Deploy to Remote Server
      env:
        HOST: ${{ secrets.SERVER_HOST }}
        USER: ${{ secrets.SERVER_USER }}
        SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        # Configure SSH key for secure access
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
        
        # Deploy the code to the remote server
        rsync -avz --exclude='node_modules' --exclude='.git' ./ $USER@$HOST:/path/to/your/app/
        
        # Run necessary commands on the remote server
        ssh $USER@$HOST 'export DB_HOST=$DB_HOST && export DB_USERNAME=$DB_USERNAME && export DB_PASSWORD=$DB_PASSWORD && cd /path/to/your/app && php artisan migrate --force && php artisan config:cache && php artisan route:cache'
